### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by josx** [nraboy/ng2-cordova-oauth#18]
Are you planning to support browser?

**Comment by nraboy** [comment]
No I am not.  JavaScript cannot control cross origin pages in a desktop web browser.  As a result callback information will never be discovered causing failure.

This library will remain compiled application only.

**Comment by larssn** [comment]
This fork seems to support it: https://github.com/stalniy/ng2-cordova-oauth . But you'll have to handle the CORS yourself, so you better have access to the server you're talking to, or it'll never work.
