### ISSUE TITLE
not getting any success data for google login through Ionic2

### ISSUE THREAD

**Issue by aanand1008** [nraboy/ng2-cordova-oauth#2]
Hi Nrayboy,

I am able to login through google, but not getting any response in promises. It's throwing error, webpage not available. But it is showing access_token in error message and also not closing child window. I have tested in chrome, emulation and device in vain.

I also tried to open google using window.open(). I am able to open google. But whatever I write as a callback function within addEventListener() is not working.

Kindly help me.

Sample code 
for Google auth--

let cordovaOauth = new CordovaOauth(
            new Google({
                clientId: "myClientId",
                appScope: ["email"], "redirectUri": "http://localhost:8100/main.html"
            }));

        //       //this.platform.ready().then(() => {
        cordovaOauth.login().then((success) => {
            this.txt1 = JSON.stringify(success);
            console.log(JSON.stringify(success));
        }, (error) => {
            this.txt1 = error;
            console.log(error);
        });

For  google.com testing
this.loginWindow = window.open('http://google.com', '_blank','location=no,clearsessioncache=yes,clearcache=yes');
this.loginWindow.addEventListener('loadstart', (event) => console.log("done"), false);

**Comment by nraboy** [comment]
Hey @aanand1008,

I see the **http://localhost:8100** which leads me to believe you are trying to serve your application.  Per the REAME, you cannot serve the application.  It must be built, then installed on a simulator or device.  You cannot serve it, you cannot live-reload it.

I tested this today and it worked fine.  My assumption is that is your problem.

Best,
