### ISSUE TITLE
New event listener for connectivity timeout

### ISSUE THREAD

**Issue by condorman** [nraboy/ng2-cordova-oauth#27]
thank you for this library!!!

I insert a new reject on page load fail during internet inactivity. I hope can be useful!

provider.js => line 48

===>
browserRef.addEventListener('loaderror', function (event) {
                browserRef.removeEventListener('exit', exitListener);
                browserRef.close();  
                reject('Error load Login page');  
});

**Comment by nraboy** [comment]
I encourage you to make a PR if you think this would be valuable.  This way you get the credit.

Best,

**Comment by nraboy** [comment]
Merged into `development` branch.
