### ISSUE TITLE
Facebook auto login not closing browser

### ISSUE THREAD

**Issue by davorpeic** [nraboy/ng2-cordova-oauth#30]
Hi,

Facebook changed a little bit a way how he handles logins from other apps, and now users can enable one click login in Safari from native app, is there a way to use Safari in place of inbrowser plugin? That way users can just login with existing info saved in Safari and avoid entering their data again.

This is one app that uses that and this is how it looks like, any way we can manage that with this plugin?

![photo 9-13-16 09 58 43](https://cloud.githubusercontent.com/assets/694091/18479103/4fe580fe-7999-11e6-8d0d-a26efcb19f97.png)

thanks

**Comment by davorpeic** [comment]
Ok, I managed to accomplish this using the tips for cache mentioned here #22 but for some reason if the first time that user opens the login, the browser doesn't get closed automatically, it gets stuck like this: When Done is pressed then it returns to the app. 

![photo 9-13-16 10 16 07](https://cloud.githubusercontent.com/assets/694091/18479645/58d7353e-799b-11e6-908f-11ac033cd2ba.png)

The second login (user is already approved the facebook app) works fine, and login is almost instant. So I guess there is missing some "close browser" call?

thanks

**Comment by nraboy** [comment]
The InAppBrowser needs to use the Cordova browser.  It cannot listen for events using the system browser.

**Comment by davorpeic** [comment]
Yes, but it still doesn't trigger close() sometimes, check the last screenshot, using the default cordova browser.. if you want I can open another issue for that bug

**Comment by nraboy** [comment]
What do your logs say and does it only happen on iOS?

**Comment by davorpeic** [comment]
Let me check and will get back thanks
