### ISSUE TITLE
core.js does not export CordovaOauth

### ISSUE THREAD

**Issue by tonyawad88** [nraboy/ng2-cordova-oauth#32]
Hello,

I am using your library in my ionic 2 app, but as soon as I upgraded to RC0, I started getting this weird error:

Error: Module .../node_modules/ng2-cordova-oauth/core.js does not export CordovaOauth (imported by .../.tmp/pages/login/login.js)

Any help is greatly appreciated. Thank you !

**Comment by nraboy** [comment]
Based on the Ionic Framework forum board, it looks like RC0 has a ton of issues.  I just upgraded to RC0 and I couldn't even get a fresh untouched project to run without errors.

I'd say this is probably related to a broken RC0 build and not this library, but I'll keep the ticket open and check back after they fix some things.

**Comment by tonyawad88** [comment]
Thank you !

**Comment by tonyawad88** [comment]
It's working for me now. Thanks !
