### ISSUE TITLE
Need to press "Done" button

### ISSUE THREAD

**Issue by olostan** [nraboy/ng2-cordova-oauth#33]
On the end of user login process, the popup window does not close automatically until user press "Done" button (on iOS). 

On console logs in auth frame I see this error: 
```
http://localhost/callback#access_token=[...]&token_type=Bearer&expires_in=3600 Failed to load resource: Could not connect to the server.
```
After user press "Done" everything works as expected.
I am using ionic 2.1.0-beta.2
cordova-plugin-whitelist: 1.3.0
Also I am using cordova-plugin-wkwebview-engine.
ng2-cordova-oauth 0.0.6

**Comment by nraboy** [comment]
The `wkwebview` plugin does not work with this library because you cannot listen to web events in the same fashion as the standard InAppBrowser.  The browser doesn't dismiss because it can't listen for the event.

**Comment by davorpeic** [comment]
Ohh, I think this could also solve my ticket? #30

**Comment by olostan** [comment]
@davorpeic The problem is to figure out where this should be fixed. I've created issue in cordova's `wkwebview-engine`  repository with request to add support of "web events" that @nraboy said is missing ( https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/58 ) Let's see

**Comment by manucorporat** [comment]
The bug was reported and a PR was submitted to InAppBrowser:
https://github.com/apache/cordova-plugin-inappbrowser/pull/187
