### ISSUE TITLE
Future of Google OAuth flow

### ISSUE THREAD

**Issue by fiznool** [nraboy/ng2-cordova-oauth#36]
Google will soon [prevent OAuth sign in via an embedded webview](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

Are there any plans for this plugin to support the Google Sign In APIs as described in the link above?

FWIW the Ionic team are recommending [this plugin](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) but it would be great to use this plugin instead if Facebook, Twitter etc. logins are also needed.

**Comment by nraboy** [comment]
Google support will eventually be phased out of this library since this library is dependent on the web view and oauth over REST rather than provider SDKs.

I recommend including what Ionic is recommending if you want to keep Google support.

**Comment by fiznool** [comment]
No problem, thanks!
