### ISSUE TITLE
Custom oauth2 provider support

### ISSUE THREAD

**Issue by dylanvdmerwe** [nraboy/ng2-cordova-oauth#4]
If I create an OAuth2 Identity Server, will this plugin allow me to specify the relevant information to authenticate and retrieve an access token from my own server?

**Comment by nraboy** [comment]
Valid question.

Right now there is no generic provider as part of the library. If you want to use it with your own identity server you'd have to fork it and add your setup.

Best,

**Comment by numerized** [comment]
Hi There, is this still the case ?

**Comment by geminiyellow** [comment]
hope have generic provider
