### ISSUE TITLE
iOS 10 - Google Login 403 Error: disallowed_useragent

### ISSUE THREAD

**Issue by ahlidap** [nraboy/ng2-cordova-oauth#41]
Hello all,

I started today to get an error when trying to do the Google Login on my app.
As son as the webview opens I got a 403 Error (google error):

> This user-agent is not permitted to make OAuth authorisation request to Google as it is classified as an embedde user-agent (also known as a web-view). Per our policy, only browser are permitted to make authorisation request to Google. We offer several libraries and samples for native apps to perform authorisation request in browser. and i followed the same procedure which is mentioned in this link https://developers.google.com/google-apps/calendar/quickstart/ios.

Any hint on this?
Thanks in advance

**Comment by nraboy** [comment]
Google released a statement back in August that it was removing support for the web view, which hybrid applications depend on:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

Google support will be dropped from ng2-cordova-oauth.  Instead you should use the Apache Cordova plugin for the Google SDKs.  It wraps the native Google SDK.

Other providers continue to work correctly.

Best,
