### ISSUE TITLE
Any plans for making this plugin conformant with the Google's new rule

### ISSUE THREAD

**Issue by tonyawad88** [nraboy/ng2-cordova-oauth#42]
Google's banning Auth using InAppBrowser as of April, any plans for switching the plugin from using the inappbrowser to using maybe the native google plus ? 

Thank you !

**Comment by nraboy** [comment]
There are no plans to integrate the native Google SDK with this plugin because this plugin was designed to strictly work with the oauth REST implementations for various providers.

For Google support I encourage you to download and use the Apache Cordova plugin for Google.

Best,
