### ISSUE TITLE
Use it with google

### ISSUE THREAD

**Issue by ducmaxime** [nraboy/ng2-cordova-oauth#45]
Hi, I try to use it with google OAuth:

1. I have activated Google+ API on https://console.developers.google.com/apis/credentials
2. I have created an ID client OAuth 
<img width="746" alt="screen shot 2016-11-24 at 20 15 57" src="https://cloud.githubusercontent.com/assets/6499846/20608510/f6643926-b282-11e6-8189-1b49397bab1c.png">

3. I have installed ng2-cordova-oauth in my ionic2 app 
4. I have configure my app 
<img width="746" alt="screen shot 2016-11-24 at 20 18 09" src="https://cloud.githubusercontent.com/assets/6499846/20608563/44c41230-b283-11e6-9367-aabc76dcef72.png">

5. I have added a button to launch auth process
<img width="755" alt="screen shot 2016-11-24 at 20 19 52" src="https://cloud.githubusercontent.com/assets/6499846/20608575/6084d25c-b283-11e6-93bc-55d9bafc9dbd.png">

6. I have started my app -> ionic emulate ios

7. I have an error 
<img width="335" alt="screen shot 2016-11-24 at 20 11 40" src="https://cloud.githubusercontent.com/assets/6499846/20608601/93233d16-b283-11e6-8fda-fbc520a92bad.png">

Can you help me ?

Thx

**Comment by nraboy** [comment]
Please read the README of this project.  It has the answers you're looking for.
