### ISSUE TITLE
App touch broken after oauth

### ISSUE THREAD

**Issue by cperezvinsite** [nraboy/ng2-cordova-oauth#57]
the oauth works fine, it returns the user but sometimes after the in app browser close the app stop responding to screen touch, i mean, it's imposible to touch any element again, then i must close the app and reopen it ...

my code is 
```ts
private oauth: OauthCordova = new OauthCordova();

  private googleProvider: Google = new Google({
    clientId: 'xxxx',
    appScope: ['email']
  })

this.oauth.logInVia(this.googleProvider).then(success => {
      if(success['access_token']){
           goHome(success)
      }
    }, error => {
      console.log("ERROR: Google", error);
    });
```
```
Your system information:

Cordova CLI: 7.0.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by nraboy** [comment]
This one is new to me.

Does this happen on Android, iOS, or both? Are you attempting to use Ionic Serve or anything similar, because that won't work correctly.

On a side note, be aware that Google is starting to block requests from the InAppBrowser in favor of their native SDKs. Even if it works for you now, it won't In the future.

Best,

**Comment by cperezvinsite** [comment]
It's happening on iOS 10, i'm using on device (iphone 6s), but I thinks I solved this problem, I remove the inappbrowser plugin version 1.7.0 and installed the inappbrowser 1.5.0 and the problem stops, but it was very strange because it only happens after a successfully oauth.
