### ISSUE TITLE
Trouble with Untappd

### ISSUE THREAD

**Issue by gabeosx** [nraboy/ng2-cordova-oauth#63]
I'm having an issue with Untappd where, after sign-in, I get an error back from Untappd stating that the redirect_url or client_id is missing. I'm not really sure how to debug this issue. If I call dialogUrl() on the class I implemented, the URL includes both of those parameters. 

I know Untappd had an OOTB implementation in ng-cordova-oauth and I looked it it... didn't see anything out of the ordinary there.

`
    // Start OAuth2
    let oauth: OauthCordova = new OauthCordova();

    interface IUntappedOptions extends IOAuthOptions {
    }

    let oauthProvider: OAuthProvider = new class extends OAuthProvider {
      protected authUrl: string = 'https://untappd.com/oauth/authenticate';
      protected defaults: Object = {
        responseType: 'token'
      };

      constructor(options: IUntappedOptions = {}) {
        super(options);
      }

    }({clientId: 'xxxxxx'} );
    console.log(oauthProvider.dialogUrl());

    this.platform.ready().then(() => {
            oauth.logInVia(oauthProvider, {location:'yes', fullscreen: 'yes'}).then(success => {
                console.log("RESULT: " + JSON.stringify(success));
            }, error => {
                console.log("ERROR: ", error);
                this.showToast('Error linking Untappd');
            });
        });
`

**Comment by gabeosx** [comment]
I found the issue myself. Untappd is not following the OAuth standard of using redirect_uri, instead they are using redirect_url. In my subclassing of OAuthProvider, I had to override the `optionsToDialogUrl` method, which leads to lots of copy/paste code.

**Comment by nraboy** [comment]
Merged into `development` branch.
