### ISSUE TITLE
Scope not working, please help

### ISSUE THREAD

**Issue by mangz001** [nraboy/ng2-cordova-oauth#9]
Hi, I tried using facebook and google, but it turns out that scope doesnt working, it returns only accesstoken for both of these

this.cordovaOauthFB = new CordovaOauth(new Facebook({clientId: "myid", appScope: ["email"]}));
this.cordovaOauthG = new CordovaOauth(new Google({clientId: "myid", appScope: ["email"]}));

example return
{"access_token":"EAAZAeHUMssqkBAAZCwNi99LVPV44NjGyiZCVC732POTZBBBN06m0xWjmLAUbFncqoXQ1YfZAsu0Sm1k2IoBGZCCSp7s9myH7uePGbrlIgfZAmjjRZA69t5g3AfgdSXM3Xr6VYEZD","expires_in":"5183380"}

**Comment by mangz001** [comment]
just in case you need how I call login, here you are : 

loginFacebook() {
      this.cordovaOauthFB.login().then((success) => {
        console.log(JSON.stringify(success));
      alert(success.access_token + ", " + success.email);
  }, (error) => {
      alert(error);
    });
  }

  loginGoogle() {
      this.cordovaOauthG.login().then((success) => {
        console.log(JSON.stringify(success));
      alert(success.access_token + ", " + success.email);
  }, (error) => {
      alert(error);
    });
  }

**Comment by nraboy** [comment]
It is only supposed to return an access token.  Scopes are permissions.  Be requesting scopes you are telling the provider that the access token returned should be able to access information based on those permissions.

With the access token you must use the APIs defined in the provider documentation.

Best,
